// examples/svelte-example/src/components/sections/IsccId.svelte
<script lang="ts">
  import { gen_iscc_id } from 'iscc-core-ts'
  import ResultDisplay from '../ResultDisplay.svelte'

  let hubId = $state(42)
  let result: Record<string, unknown> | null = $state(null)
  let error = $state('')

  function generate() {
    error = ''
    try {
      const res = gen_iscc_id(hubId)
      result = res as Record<string, unknown>
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
      result = null
    }
  }
</script>

<div id="iscc-id" class="section">
  <div class="section-header">
    <span class="section-dot" style="background: var(--color-iscc-id)"></span>
    <h2>ISCC-ID</h2>
  </div>
  <p class="section-desc">
    Generates a globally unique, owned identifier based on a timestamp and HUB-ID.
    The 52-bit UTC timestamp + 12-bit HUB-ID ensures uniqueness across distributed systems.
  </p>

  <div class="form-row">
    <div class="form-group">
      <label for="iscc-id-hub">HUB ID (0–4095)</label>
      <input
        id="iscc-id-hub"
        class="form-input"
        type="number"
        min="0"
        max="4095"
        bind:value={hubId}
      />
    </div>
    <div class="form-group">
      <button class="btn btn-primary" onclick={generate}>
        Generate ISCC-ID
      </button>
    </div>
  </div>

  <ResultDisplay
    {error}
    iscc={result?.iscc as string | undefined}
    raw={result}
  />
</div>

// examples/react-example/src/components/sections/IsccId.tsx
import { useState, useCallback } from 'react'
import { gen_iscc_id } from 'iscc-core-ts'
import ResultDisplay from '../ResultDisplay'

export default function IsccId() {
  const [hubId, setHubId] = useState(42)
  const [result, setResult] = useState<Record<string, unknown> | null>(null)
  const [error, setError] = useState('')

  const generate = useCallback(() => {
    setError('')
    try {
      const res = gen_iscc_id(hubId)
      setResult(res as Record<string, unknown>)
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
      setResult(null)
    }
  }, [hubId])

  return (
    <div id="iscc-id" className="section">
      <div className="section-header">
        <span className="section-dot" style={{ background: 'var(--color-iscc-id)' }} />
        <h2>ISCC-ID</h2>
      </div>
      <p className="section-desc">
        Generates a globally unique, owned identifier based on a timestamp and HUB-ID.
        The 52-bit UTC timestamp + 12-bit HUB-ID ensures uniqueness across distributed systems.
      </p>

      <div className="form-row">
        <div className="form-group">
          <label>HUB ID (0–4095)</label>
          <input
            className="form-input"
            type="number"
            min={0}
            max={4095}
            value={hubId}
            onChange={(e) => setHubId(Number(e.target.value))}
          />
        </div>
        <div className="form-group">
          <button className="btn btn-primary" onClick={generate}>
            Generate ISCC-ID
          </button>
        </div>
      </div>

      <ResultDisplay
        error={error}
        iscc={result?.iscc as string | undefined}
        raw={result}
      />
    </div>
  )
}
