// examples/react-example/src/components/sections/TextCode.tsx
import { useState, useCallback } from 'react'
import { gen_text_code } from 'iscc-core-ts'
import ResultDisplay from '../ResultDisplay'

export default function TextCode() {
  const [text, setText] = useState('The quick brown fox jumps over the lazy dog. This is a sample text for demonstrating the ISCC Content-Code Text generation algorithm which uses MinHash for similarity hashing.')
  const [bits, setBits] = useState(64)
  const [result, setResult] = useState<Record<string, unknown> | null>(null)
  const [error, setError] = useState('')

  const generate = useCallback(() => {
    setError('')
    try {
      const res = gen_text_code(text, bits)
      setResult(res as Record<string, unknown>)
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
      setResult(null)
    }
  }, [text, bits])

  return (
    <div id="text" className="section">
      <div className="section-header">
        <span className="section-dot" style={{ background: 'var(--color-content)' }} />
        <h2>Content-Code Text</h2>
      </div>
      <p className="section-desc">
        Generates a similarity hash from text content using character-level n-gram shingling and MinHash.
        Similar texts produce similar codes.
      </p>

      <div className="form-group">
        <label>Text Content</label>
        <textarea className="form-textarea" value={text} onChange={(e) => setText(e.target.value)} rows={5} placeholder="Enter text..." />
      </div>
      <div className="form-row">
        <div className="form-group">
          <label>Bits</label>
          <select className="form-select" value={bits} onChange={(e) => setBits(Number(e.target.value))}>
            <option value={64}>64</option>
            <option value={128}>128</option>
            <option value={256}>256</option>
          </select>
        </div>
        <div className="form-group">
          <button className="btn btn-primary" onClick={generate} disabled={!text}>
            Generate Text-Code
          </button>
        </div>
      </div>

      <ResultDisplay
        error={error}
        iscc={result?.iscc as string | undefined}
        fields={result ? [
          { label: 'Characters', value: result.characters as number },
        ] : undefined}
        raw={result}
      />
    </div>
  )
}

// examples/svelte-example/src/components/sections/TextCode.svelte
<script lang="ts">
  import { gen_text_code } from 'iscc-core-ts'
  import ResultDisplay from '../ResultDisplay.svelte'

  let text = $state('The quick brown fox jumps over the lazy dog. This is a sample text for demonstrating the ISCC Content-Code Text generation algorithm which uses MinHash for similarity hashing.')
  let bits = $state(64)
  let result: Record<string, unknown> | null = $state(null)
  let error = $state('')

  function generate() {
    error = ''
    try {
      const res = gen_text_code(text, bits)
      result = res as Record<string, unknown>
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
      result = null
    }
  }

  let fields = $derived(result ? [
    { label: 'Characters', value: result.characters as number },
  ] : undefined)
</script>

<div id="text" class="section">
  <div class="section-header">
    <span class="section-dot" style="background: var(--color-content)"></span>
    <h2>Content-Code Text</h2>
  </div>
  <p class="section-desc">
    Generates a similarity hash from text content using character-level n-gram shingling and MinHash.
    Similar texts produce similar codes.
  </p>

  <div class="form-group">
    <label for="text-content">Text Content</label>
    <textarea id="text-content" class="form-textarea" bind:value={text} rows="5" placeholder="Enter text..."></textarea>
  </div>
  <div class="form-row">
    <div class="form-group">
      <label for="text-bits">Bits</label>
      <select id="text-bits" class="form-select" bind:value={bits}>
        <option value={64}>64</option>
        <option value={128}>128</option>
        <option value={256}>256</option>
      </select>
    </div>
    <div class="form-group">
      <button class="btn btn-primary" onclick={generate} disabled={!text}>
        Generate Text-Code
      </button>
    </div>
  </div>

  <ResultDisplay
    {error}
    iscc={result?.iscc as string | undefined}
    {fields}
    raw={result}
  />
</div>
